"""empty message

Revision ID: fb35238fadc3
Revises: d56a75890a36
Create Date: 2020-12-08 05:36:12.077398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb35238fadc3'
down_revision = 'd56a75890a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.create_foreign_key(None, 'Assignment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Assignment', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.create_foreign_key(None, 'Assignment', 'task', ['task_id'], ['id'])
    op.create_foreign_key(None, 'Assignment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
